### ISSUE TITLE
Error: utils/throttle Type 'number' is not assignable to type 'Timeout | null' 

### ISSUE THREAD

**Issue by Adam16** [koala-interactive/react-anchor-navigation#7]
Hey,
apparently there are errors in the throttle helper.

`let timeout: NodeJS.Timeout | null = null;`

**TS2322: Type 'number' is not assignable to type 'Timeout | null'.**

node: v12.13.1
TS: 3.9.4
React: 16.13.1

**Comment by vthibault** [comment]
Thanks for the report !
The fix is now available on the 0.2.4 version !
